version: 0.0
os: linux
files:
  - source: /frontend/
    destination: /home/ec2-user/server_based_app/frontend/
    overwrite: true
  - source: /backend/
    destination: /home/ec2-user/server_based_app/backend/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root